# docker-compose.yml

version: "3.5"
services:
  server:
    build:
      context: ./server
    restart: always
    ports:
      - 3005:3005
    networks:
      - db-net
    depends_on:
      - db
  client:
    build:
      context: ./client
    restart: always
    ports:
      - 3000:3000
  db:
    image: mysql:8.1.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: edurootroot
    hostname: movie
    networks:
      - db-net
    ports:
      - 9086:3306

networks:
  db-net: